### 회원가입
POST http://localhost:3000/auth/signup
Content-Type: application/json 

{
    "email": "test33@example.com",
    "password": "Test123@#",
    "confirmPassword": "Test123@#",
    "nickname" : "test12"
}

### 로그인
POST http://localhost:3000/auth/login
Content-Type: application/json 

{
    "email": "test33@example.com",
    "password": "Test123@#"
}

### 로그아웃
POST http://localhost:3000/auth/logout
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwibmlja25hbWUiOiJ0ZXN0MTIiLCJpYXQiOjE3NTM5NzA4MDksImV4cCI6MTc1Mzk3NDQwOX0.VRZv7G_hZdScTZCI7daQ1ozpaCeaYQZrmDvc26yPiY8; refreshToken=refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNzUzOTcwODA5LCJleHAiOjE3NTQ1NzU2MDl9.ej15xR70duk8fWgBEFfT3gPFMf01oM0T4qCH1M7nkxk;

Content-Type: application/json

### 판매 목록 조회
GET http://localhost:3000/sales
Content-Type: application/json