### 회원가입
POST http://localhost:3000/auth/signup
Content-Type: application/json 

{
    "email": "test33@example.com",
    "password": "Test123@#",
    "confirmPassword": "Test123@#",
    "nickname" : "test12"
}

### 로그인
POST http://localhost:3000/auth/login
Content-Type: application/json 

{
    "email": "test33@example.com",
    "password": "Test123@#"
}